/aruco_analyzer:  # Имя узла (или namespace/узел)
  ros__parameters:
    enable_debug_flow: false
    enable_rviz_markers: false
    aruco_dictionary: "DICT_6X6_250"
    marker_size: 0.12
    camera_topic: "/camera/image_raw/compressed"
    camera_info_topic: "/camera/camera_info"
    output_image_topic: "/aruco/debug_image/compressed"
    output_poses_topic: "/aruco/markers"
    rviz_markers_topic: "/aruco/markers_rviz"