/aruco_analyzer: 
  ros__parameters:
    enable_logging: false
    enable_debug_flow: false
    enable_rviz_markers: false
    aruco_dictionary: "DICT_5X5_250"
    marker_size: 0.03
    camera_topic: "/camera/image/compressed"
    camera_info_topic: "/camera/camera_info"
    output_image_topic: "/aruco/image/compressed"
    output_camera_info_topic: '/aruco/camera_info'
    output_poses_topic: "/aruco/markers"
    rviz_markers_topic: "/aruco/markers_rviz"
    